### ISSUE TITLE
pyopencv_generated_include.h not found

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [NeerajGulia/python-opencv-cuda#1]
Thanks for adding this tutorial.

I was able to `cmake` and `make`, following your instructions, however the process failed during
`sudo make install` with the error message:

```bash
/home/user/src/opencv-3.4.2/modules/python/src2/cv2.cpp:30:40: fatal error: pyopencv_generated_include.h: No such file or directory
compilation terminated.
```

This is from one fo your files. Any idea why that file was not generated?

**Comment by Nicholas-Autio-Mitchell** [comment]
I still haven't been able to fix the bug, but it seems the following function from `modules/python/src2/gen2.py` in the `PythonWrapperGenerator` class is somehow not doing its job:

```python
    def gen(self, srcfiles, output_path):
        self.clear()
        self.parser = hdr_parser.CppHeaderParser(generate_umat_decls=True)

        # step 1: scan the headers and build more descriptive maps of classes, consts, functions
        for hdr in srcfiles:
            decls = self.parser.parse(hdr)
            if len(decls) == 0:
                continue
            self.code_include.write( '#include "{0}"\n'.format(hdr[hdr.rindex('opencv2/'):]) )
            for decl in decls:
                name = decl[0]
                if name.startswith("struct") or name.startswith("class"):
                    # class/struct
                    p = name.find(" ")
                    stype = name[:p]
                    name = name[p+1:].strip()
                    self.add_class(stype, name, decl)
                elif name.startswith("const"):
                    # constant
                    self.add_const(name.replace("const ", "").strip(), decl)
                else:
                    # function
                    self.add_func(decl)
```

I can only imagine that the `pyopencv_generated_include.h` file is not being created, due to the condition that some header files must include it. If there aren't any, it doesn't get created, but the make process still tries to include it somewhere.

**Comment by Nicholas-Autio-Mitchell** [comment]
@NeerajGulia 

Pausing after running `cmake`, I can see that the files have not been generated at that point.
Maybe they get generated during the `make` build process, but I do no know how to check that.

Any help would be appreciated!

**Comment by NeerajGulia** [comment]
you may have to manually execute the generator script (gen2.py)

Assuming you called cmake .. from the build directory you could do:

python ./modules/python/src2/gen2.py ./build/modules/python_bindings_generator ./build/modules/python_bindings_generator/headers.txt

I think the bug arises because cmake doesn't find the right python executable to run the script.

Source: https://github.com/opencv/opencv/issues/10771#issuecomment-376861139

**Comment by Nicholas-Autio-Mitchell** [comment]
Thanks you, I managed to make it work!

I did have to change the `cmake` command to deactivate the options including **TBB**. For some reason I could no execute your cpu-/ and gpu-opt_flow.py scripts with TBB included.

I also had to include an explicit path for the Python interpreter to be used for the build via `-DPYTHON_DEFAULT_EXECUTABLE=`.

Here was the edited command:

```
cmake \
-DCMAKE_BUILD_TYPE=RELEASE \
-DWITH_CUDA=ON\
-DCMAKE_INSTALL_PREFIX="/home/$USER/anaconda3/envs/cvcuda" \
-DOPENCV_EXTRA_MODULES_PATH="../../opencv_contrib-3.4.2/modules" \
-DINSTALL_PYTHON_EXAMPLES=OFF \
-DINSTALL_C_EXAMPLES=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_DOCS=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_opencv_dnn=OFF \
-DTINYDNN_USE_NNPACK=OFF \
-DTINYDNN_USE_TBB=OFF \
-DTINYDNN_USE_OMP=ON \
-DENABLE_FAST_MATH=ON \
-DWITH_OPENMP=ON \
-DWITH_TBB=OFF \
-DWITH_JPEG=OFF \
-DWITH_IPP=OFF \
-DMKL_WITH_TBB=OFF \
-DMKL_WITH_OPENMP=ON \
-DBUILD_opencv_python2=OFF \
-DPYTHON_EXECUTABLE="/home/$USER/anaconda3/envs/cvcuda/bin/python" \
-DPYTHON_LIBRARY="/home/$USER/anaconda3/envs/cvcuda/lib/python3.6" \
-DPYTHON3_LIBRARY="/home/$USER/anaconda3/envs/cvcuda/lib/python3.6" \
-DPYTHON3_EXECUTABLE="/home/$USER/anaconda3/envs/cvcuda/bin/python" \
-DPYTHON3_INCLUDE_DIR="/home/$USER/anaconda3/envs/cvcuda/include/python3.6m" \
-DPYTHON3_INCLUDE_DIR2="/home/$USER/anaconda3/envs/cvcuda/include" \
-DPYTHON3_NUMPY_INCLUDE_DIRS="/home/$USER/anaconda3/envs/cvcuda/lib/python3.6/site-packages/numpy/core/include" \
-DPYTHON3_INCLUDE_PATH="/home/$USER/anaconda3/envs/cvcuda/include/python3.6m" \
-DPYTHON3_LIBRARIES="/home/$USER/anaconda3/envs/cvcuda/lib/libpython3.6m.so" \
-DPYTHON_DEFAULT_EXECUTABLE="/home/$USER/anaconda3/envs/cvcuda/bin/python" \
..

```

And here are my timings  :smile:   

```rust
(cvcuda) nicholas@mitchell:~/src/opencv_contrib-3.4.2/modules/python-opencv-cuda-master/python$ python cpu-opt_flow.py 
total time in optical flow CPU processing: 141.1896 sec, for: 794 frames. FPS: 5.62
(cvcuda) nicholas@mitchell:~/src/opencv_contrib-3.4.2/modules/python-opencv-cuda-master/python$ python gpu-opt_flow.py 
total time in optical flow GPU processing: 36.5423 sec, for: 794 frames. FPS: 21.73
```

**Comment by NeerajGulia** [comment]
I am glad it worked, and you were successfully able to execute the GPU Optical Flow using Pytho.

Three Cheers.
